/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jaokim_dumpster_Divider */

#ifndef _Included_jaokim_dumpster_Divider
#define _Included_jaokim_dumpster_Divider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jaokim_dumpster_Divider
 * Method:    native_div_call
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jaokim_dumpster_Divider_native_1div_1call
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
