/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_oracle_jaokim_dumpster_Dumpster */

#ifndef _Included_se_oracle_jaokim_dumpster_Dumpster
#define _Included_se_oracle_jaokim_dumpster_Dumpster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_oracle_jaokim_dumpster_Dumpster
 * Method:    div_operator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_se_oracle_jaokim_dumpster_Dumpster_div_1operator
  (JNIEnv *, jobject, jint);

/*
 * Class:     se_oracle_jaokim_dumpster_Dumpster
 * Method:    div_call
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_se_oracle_jaokim_dumpster_Dumpster_div_1call
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
